### PR TITLE
Replaced a tab by a few space because of the following message:

### PR DESCRIPTION
**Pull request by dglaude**
> Sorry: TabError: inconsistent use of tabs and spaces in indentation (led.py, line 302)

### CODE REVIEW

**Comment by dglaude** [comment]
Apparently your code is python2 as in the example you use xrange.
Maybe python2 is more tolerant to space and tab mixing?

**Comment by bennuttall** [comment]
I was about to do the same PR. Wanted to look at how easy it would be to make this work in Python 3...

**Comment by dglaude** [comment]
Does @AverageManVsPi or PiHUT selling the product care about the software that support the hardware? Nowdays, I believe all the library and example for Raspberry Pi gadget and accessories should be Python3 compatible.

Regards

**Comment by rm-hull** [comment]
@dglaude: try using https://github.com/rm-hull/luma.led_matrix - this is actively maintained (by me & a few others), supports py2/3, has documentation & automated tests, installs from pypi, etc.

It was the original library that averagemanvspi forked for this repo. Things have moved on considerably in the original since the fork occurred however.

**Comment by dglaude** [comment]
Thanks.

2017-06-10 17:14 GMT+02:00 Richard Hull <notifications@github.com>:

**Comment by AverageMaker** [comment]
> @dglaude: try using https://github.com/rm-hull/luma.led_matrix - this is actively maintained (by me & a few others), supports py2/3, has documentation & automated tests, installs from pypi, etc.
> 
> It was the original library that averagemanvspi forked for this repo. Things have moved on considerably in the original since the fork occurred however.

Hi Richard. I've returned to look at this as a favour, as the product IP was actually transferred to The Pi Hut a long time ago. I probably should have maintained the library but a lot has gone on since then.

Anyway, I see two key issues with this old fork:

1. Python 2 vs Python 3. As Python 3 is clearly the way forward, a 'fresh' fork of Luma seems like a good idea - unfortunately I'm not sure how to do this without breaking the code or links to the fork.
2. There was a change to SPI on the Raspberry Pi/Raspbian a while back that seemed to break the ZeroSeg, however it appears to work with your updated Luma library. Similar to above, it would be good to pull a new fork to do this.

I don't mind manually working through the code to customise it again for the ZeroSeg if I have to, it's just doing it without breaking stuff that I'm worried about.

If possible, I'd love to take this to email/Google Hangouts or similar if you could spare the time to help me? Unfortunately I'm just not that great with Github! I'll drop you an email from my new email address.

**Comment by AverageMaker** [comment]
I have just updated the repo which included removing inconsistencies in indentation. I'm still reasonably new to Python3 so haven't tackled it from that angle yet.

**Pull request closed without merging**
